In [3]:

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [4]:
# Create an SQLite database
conn = sqlite3.connect("workforce_analytics.db")

print("Database connected successfully!")

Database connected successfully!

In [ ]:
#2. Create the Employee table

In [5]:
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS Employees (
    Employee_ID INTEGER PRIMARY KEY,
    Employee_Name TEXT,
    Age INTEGER,
    Gender TEXT,
    Department TEXT,
    Job_Role TEXT,
    Location TEXT,
    Education TEXT,
    Experience_Years INTEGER,
    Salary REAL,
    Performance_Score REAL,
    Job_Satisfaction INTEGER,
    Engagement_Score INTEGER,
    Training_Hours INTEGER,
    Promotions INTEGER,
    Remote_Work TEXT,
    Attrition TEXT,
    Joining_Date DATE
)
""")

conn.commit()

print("Employees table created successfully!")

Employees table created successfully!

In [ ]:
#3. Insert sample workforce data

In [6]:
employees = [
    (1, 'Rahul', 28, 'Male', 'IT', 'Software Engineer', 'Hyderabad', 'B.Tech', 4, 65000, 4.2, 4, 85, 40, 1, 'Yes', 'No', '2022-01-15'),
    (2, 'Priya', 32, 'Female', 'HR', 'HR Manager', 'Bangalore', 'MBA', 8, 85000, 4.5, 5, 92, 35, 2, 'Yes', 'No', '2019-03-20'),
    (3, 'Arjun', 26, 'Male', 'IT', 'Data Analyst', 'Hyderabad', 'B.Tech', 2, 55000, 3.8, 3, 70, 20, 0, 'No', 'Yes', '2023-06-10'),
    (4, 'Sneha', 29, 'Female', 'Finance', 'Financial Analyst', 'Chennai', 'MBA', 5, 60000, 4.0, 4, 80, 30, 1, 'Yes', 'No', '2021-07-12'),
    (5, 'Vikram', 35, 'Male', 'IT', 'Technical Lead', 'Hyderabad', 'M.Tech', 11, 110000, 4.7, 5, 95, 50, 3, 'Yes', 'No', '2016-02-18'),
    (6, 'Ananya', 25, 'Female', 'Marketing', 'Marketing Executive', 'Mumbai', 'MBA', 2, 48000, 3.5, 2, 60, 10, 0, 'No', 'Yes', '2024-01-05'),
    (7, 'Kiran', 31, 'Male', 'IT', 'Cloud Engineer', 'Bangalore', 'B.Tech', 7, 90000, 4.3, 4, 88, 45, 1, 'Yes', 'No', '2020-05-22'),
    (8, 'Divya', 27, 'Female', 'HR', 'Recruiter', 'Hyderabad', 'MBA', 3, 52000, 3.9, 3, 75, 25, 0, 'Yes', 'No', '2022-09-15'),
    (9, 'Rohit', 30, 'Male', 'Finance', 'Senior Accountant', 'Pune', 'M.Com', 6, 70000, 4.1, 4, 82, 32, 1, 'No', 'No', '2020-11-10'),
    (10, 'Meena', 34, 'Female', 'IT', 'Project Manager', 'Hyderabad', 'MBA', 10, 105000, 4.6, 5, 94, 48, 2, 'Yes', 'No', '2017-04-25'),
    (11, 'Suresh', 29, 'Male', 'Sales', 'Sales Executive', 'Delhi', 'BBA', 4, 58000, 3.6, 2, 65, 15, 0, 'No', 'Yes', '2022-03-12'),
    (12, 'Lakshmi', 38, 'Female', 'IT', 'Data Scientist', 'Bangalore', 'M.Tech', 12, 120000, 4.8, 5, 97, 60, 3, 'Yes', 'No', '2015-08-17'),
    (13, 'Amit', 27, 'Male', 'IT', 'Software Developer', 'Pune', 'B.Tech', 3, 62000, 3.9, 3, 76, 25, 0, 'No', 'No', '2023-02-20'),
    (14, 'Pooja', 33, 'Female', 'Marketing', 'Marketing Manager', 'Mumbai', 'MBA', 9, 88000, 4.4, 4, 89, 40, 2, 'Yes', 'No', '2018-10-11'),
    (15, 'Naveen', 24, 'Male', 'IT', 'Junior Developer', 'Hyderabad', 'B.Tech', 1, 45000, 3.2, 2, 55, 8, 0, 'No', 'Yes', '2024-06-01')
]

cursor.executemany("""
INSERT OR IGNORE INTO Employees
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", employees)

conn.commit()

print("Employee data inserted successfully!")

Employee data inserted successfully!

In [ ]:
#4. Display all employees

In [7]:
query = """
SELECT * FROM Employees;
"""

df = pd.read_sql_query(query, conn)
df

,Employee_ID,Employee_Name,Age,Gender,Department,Job_Role,Location,Education,Experience_Years,Salary,Performance_Score,Job_Satisfaction,Engagement_Score,Training_Hours,Promotions,Remote_Work,Attrition,Joining_Date
0,1,Rahul,28,Male,IT,Software Engineer,Hyderabad,B.Tech,4,65000.0,4.2,4,85,40,1,Yes,No,2022-01-15
1,2,Priya,32,Female,HR,HR Manager,Bangalore,MBA,8,85000.0,4.5,5,92,35,2,Yes,No,2019-03-20
2,3,Arjun,26,Male,IT,Data Analyst,Hyderabad,B.Tech,2,55000.0,3.8,3,70,20,0,No,Yes,2023-06-10
3,4,Sneha,29,Female,Finance,Financial Analyst,Chennai,MBA,5,60000.0,4.0,4,80,30,1,Yes,No,2021-07-12
4,5,Vikram,35,Male,IT,Technical Lead,Hyderabad,M.Tech,11,110000.0,4.7,5,95,50,3,Yes,No,2016-02-18
5,6,Ananya,25,Female,Marketing,Marketing Executive,Mumbai,MBA,2,48000.0,3.5,2,60,10,0,No,Yes,2024-01-05
6,7,Kiran,31,Male,IT,Cloud Engineer,Bangalore,B.Tech,7,90000.0,4.3,4,88,45,1,Yes,No,2020-05-22
7,8,Divya,27,Female,HR,Recruiter,Hyderabad,MBA,3,52000.0,3.9,3,75,25,0,Yes,No,2022-09-15
8,9,Rohit,30,Male,Finance,Senior Accountant,Pune,M.Com,6,70000.0,4.1,4,82,32,1,No,No,2020-11-10
9,10,Meena,34,Female,IT,Project Manager,Hyderabad,MBA,10,105000.0,4.6,5,94,48,2,Yes,No,2017-04-25
10,11,Suresh,29,Male,Sales,Sales Executive,Delhi,BBA,4,58000.0,3.6,2,65,15,0,No,Yes,2022-03-12
11,12,Lakshmi,38,Female,IT,Data Scientist,Bangalore,M.Tech,12,120000.0,4.8,5,97,60,3,Yes,No,2015-08-17
12,13,Amit,27,Male,IT,Software Developer,Pune,B.Tech,3,62000.0,3.9,3,76,25,0,No,No,2023-02-20
13,14,Pooja,33,Female,Marketing,Marketing Manager,Mumbai,MBA,9,88000.0,4.4,4,89,40,2,Yes,No,2018-10-11
14,15,Naveen,24,Male,IT,Junior Developer,Hyderabad,B.Tech,1,45000.0,3.2,2,55,8,0,No,Yes,2024-06-01

In [8]:
#Query 1 — Count total employees
query = """
SELECT COUNT(*) AS Total_Employees
FROM Employees;
"""

pd.read_sql_query(query, conn)

   Total_Employees
0               15

In [9]:
#2 — Employees by department
query = """
SELECT Department, COUNT(*) AS Employee_Count
FROM Employees
GROUP BY Department;
"""

pd.read_sql_query(query, conn)

  Department  Employee_Count
0    Finance               2
1         HR               2
2         IT               8
3  Marketing               2
4      Sales               1

In [10]:
#3 — Average salary by department
query = """
SELECT
    Department,
    ROUND(AVG(Salary), 2) AS Average_Salary
FROM Employees
GROUP BY Department;
"""

pd.read_sql_query(query, conn)

  Department  Average_Salary
0    Finance         65000.0
1         HR         68500.0
2         IT         81500.0
3  Marketing         68000.0
4      Sales         58000.0

In [11]:
#4 — Average performance by department
query = """
SELECT
    Department,
    ROUND(AVG(Performance_Score), 2) AS Average_Performance
FROM Employees
GROUP BY Department;
"""

pd.read_sql_query(query, conn)

  Department  Average_Performance
0    Finance                 4.05
1         HR                 4.20
2         IT                 4.19
3  Marketing                 3.95
4      Sales                 3.60

In [12]:
#5 — Find employees with high performance
query = """
SELECT Employee_Name, Department, Job_Role, Performance_Score
FROM Employees
WHERE Performance_Score >= 4.5;
"""

pd.read_sql_query(query, conn)

  Employee_Name Department         Job_Role  Performance_Score
0         Priya         HR       HR Manager                4.5
1        Vikram         IT   Technical Lead                4.7
2         Meena         IT  Project Manager                4.6
3       Lakshmi         IT   Data Scientist                4.8

In [13]:
#Attrition Analysis
#6 — Employees who left
query = """
SELECT *
FROM Employees
WHERE Attrition = 'Yes';
"""

pd.read_sql_query(query, conn)

,Employee_ID,Employee_Name,Age,Gender,Department,Job_Role,Location,Education,Experience_Years,Salary,Performance_Score,Job_Satisfaction,Engagement_Score,Training_Hours,Promotions,Remote_Work,Attrition,Joining_Date
0,3,Arjun,26,Male,IT,Data Analyst,Hyderabad,B.Tech,2,55000.0,3.8,3,70,20,0,No,Yes,2023-06-10
1,6,Ananya,25,Female,Marketing,Marketing Executive,Mumbai,MBA,2,48000.0,3.5,2,60,10,0,No,Yes,2024-01-05
2,11,Suresh,29,Male,Sales,Sales Executive,Delhi,BBA,4,58000.0,3.6,2,65,15,0,No,Yes,2022-03-12
3,15,Naveen,24,Male,IT,Junior Developer,Hyderabad,B.Tech,1,45000.0,3.2,2,55,8,0,No,Yes,2024-06-01

In [14]:
#7 — Attrition count
query = """
SELECT
    Attrition,
    COUNT(*) AS Employee_Count
FROM Employees
GROUP BY Attrition;
"""

pd.read_sql_query(query, conn)

  Attrition  Employee_Count
0        No              11
1       Yes               4

In [15]:
#8 — Attrition rate
query = """
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*), 2
    ) AS Attrition_Rate
FROM Employees;
"""

pd.read_sql_query(query, conn)

   Attrition_Rate
0           26.67

In [16]:
#9 — Attrition by department
query = """
SELECT
    Department,
    COUNT(*) AS Total_Employees,
    SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) AS Attrition_Count,
    ROUND(
        100.0 * SUM(CASE WHEN Attrition = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2
    ) AS Attrition_Rate
FROM Employees
GROUP BY Department;
"""

pd.read_sql_query(query, conn)

  Department  Total_Employees  Attrition_Count  Attrition_Rate
0    Finance                2                0             0.0
1         HR                2                0             0.0
2         IT                8                2            25.0
3  Marketing                2                1            50.0
4      Sales                1                1           100.0